import './utils/console-wrapper.js';
import './utils/qunit-utils.js';

// src/math
import './src/math/Box2.tests.js';
import './src/math/Box3.tests.js';
import './src/math/Color.tests.js';
import './src/math/Cylindrical.tests.js';
import './src/math/Euler.tests.js';
import './src/math/Interpolant.tests.js';
import './src/math/Line3.tests.js';
import './src/math/MathUtils.tests.js';
import './src/math/Matrix3.tests.js';
import './src/math/Matrix4.tests.js';
import './src/math/Plane.tests.js';
import './src/math/Quaternion.tests.js';
import './src/math/Ray.tests.js';
import './src/math/Sphere.tests.js';
import './src/math/Spherical.tests.js';
import './src/math/Triangle.tests.js';
import './src/math/Vector2.tests.js';
import './src/math/Vector3.tests.js';
import './src/math/Vector4.tests.js';

// src/math/interpolants
import './src/math/interpolants/CubicInterpolant.tests.js';
import './src/math/interpolants/DiscreteInterpolant.tests.js';
import './src/math/interpolants/LinearInterpolant.tests.js';
import './src/math/interpolants/QuaternionLinearInterpolant.tests.js';
